services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fra-stratos-trading-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development
    volumes:
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
